import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { cookies } from 'next/headers'
import NextTopLoader from 'nextjs-toploader'
import { CookieBanner } from '@/components/layout/cookies-banner'
import { AppProvider } from '@/providers/app-provider'
import './globals.css'

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-jakarta-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const cookieStore = await cookies()
  const hasConsentCookie = cookieStore.has('cookie-consent')

  return (
    <html
      lang="en"
      className={`${plusJakarta.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head />
      <body className="min-h-full flex flex-col">
        <NextTopLoader showSpinner={false} color="#1447e6" height={3} />
        <AppProvider>{children}</AppProvider>
        {!hasConsentCookie && <CookieBanner />}
      </body>
    </html>
  )
}
