import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { cookies } from 'next/headers'
import { getLocale, getMessages } from 'next-intl/server'
import NextTopLoader from 'nextjs-toploader'
import { CookieBanner } from '@/components/layout/cookies-banner'
import { routing } from '@/i18n/routing'
import { AppProvider } from '@/providers/app-provider'
import '../globals.css'

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-jakarta-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return routing.locales.map((loc) => ({ locale: loc }))
}

export default async function RootLayout({ children }: LayoutProps<'/[locale]'>) {
  const currentLocale = await getLocale()
  const cookieStore = await cookies()
  const hasConsentCookie = cookieStore.has('cookie-consent')
  const messages = await getMessages()

  return (
    <html
      lang={currentLocale}
      className={`${plusJakarta.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head />
      <body className="min-h-full flex flex-col">
        <NextTopLoader showSpinner={false} color="#1447e6" height={3} />
        <AppProvider locale={currentLocale} messages={messages}>
          {!hasConsentCookie && <CookieBanner />}
          {children}
        </AppProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
